name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      sha256sums:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest 
    steps:
      - run: 'echo ${{ inputs.version }}'
      - run: |
          echo ${{ fromJson(inputs.sha256sums)['keyweave-x86_64-unknown-linux-musl.tar.xz'] }}