name: End-to-end tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Formula/keyweave.rb"

jobs:
  hosted:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-13
          - macos-12
          - macos-11

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check installation using Homebrew
        run: |
          if ! command -v brew &> /dev/null
          then
              echo "Homebrew not found, installing..."
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
              eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          else
              echo "Homebrew is already installed."
          fi
          brew tap bartvdbraak/keyweave
          brew install keyweave
          keyweave --version
  emulated:
    name: Test on raspios-lite
    runs-on: ubuntu-latest
  
    steps:
      - uses: pguyot/arm-runner-action@v2.5.2
        with:
          commands: |
            if ! command -v brew &> /dev/null
            then
                echo "Homebrew not found, installing..."
                su pi -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            else
                echo "Homebrew is already installed."
            fi
            su pi -c /usr/local/bin/brew tap bartvdbraak/keyweave
            su pi -c /usr/local/bin/brew install keyweave
            su pi -c keyweave --version